### ISSUE TITLE
Twig Error When Using "byCategory" Filter

### ISSUE THREAD

**Issue by theskyfloor** [tippingmedia/craft.events#4]
Template Error

A hash key must be followed by a colon (:). Unexpected token "punctuation" of value "," ("punctuation" expected with value ":")

/Users/Alan/Sites/vcob/craft/templates/index.html(123)

111             
112             <h2>Light Fixtures Workday</h2>
113             <h3>[+] Photo Gallery</h3>
114             
115           </div>
116         </div>
117       </div>
118 
119       <div class="section-title"><h2>Events</h2><span class="line"></span></div>
120 
121       {% set order = false %}
122       {% set filters = {
123           byCategory:{'home page','test'},
124           page:{offset:0,howmany:4}
125           }
126       %}
127       {% set dateFilters = {
128           Past:false,
129           byYear: now|date('Y')
130           }
131       %}
132 
133       {% set events = craft.Events.getAllEvents(order,filters,dateFilters) %}
134

**Comment by theskyfloor** [comment]
Any potential help on this? I would love to be able to sort based on category.

**Comment by a-am** [comment]
Currently the field name for categories needs to be named "Event Categories".  In a future update I plan to open that up.  Is your category field named differently?

**Comment by theskyfloor** [comment]
It is... I tried to change that reference in Events_EventManageService.php on line 144 but I am still getting the same error. Sorry for spamming you on twitter too! Did it before you responded here.

**Comment by a-am** [comment]
Have you downloaded latest version?

**Comment by theskyfloor** [comment]
Yeah I updated today before I started on this again. At this point I am very curious about why it isn't working : ) Seems like the field reference should have solved the problem.

**Comment by theskyfloor** [comment]
I am happy to troubleshoot it in anyway you want tonight... let me know.

**Comment by a-am** [comment]
Try the categories filter like this: 
 `byCategory:['home page':'test']`
instead of:
`byCategory:{'home page':'test'}`

**Comment by theskyfloor** [comment]
You rock! I should have tried that anyway... Would it be possible in the future to sort based on two different category fields - it isn't necessary but sometimes I set up sites like that. Or maybe sort based on a "featured" light switch field or are sorting options like that available to the craft.Events tag natively?

Thanks again for your help.

**Comment by a-am** [comment]
I will update the docs.  In the future I hope to add ability to search by more than just one category field. I don't have a timeline for those features yet.
