### ISSUE TITLE
No results when specifying year and month in dateFilter

### ISSUE THREAD

**Issue by etx** [tippingmedia/craft.events#5]
craft.Events.getAllEvents(true, {}, {byYear:'2015', byMonth:'january'} ) | groupByDate('day')

I'm not seeing any results from this query, but if I remove year or month (leaving only one of the filters) it works fine. I have entries in my database that should be shown. I'm building a linear calendar of events that I want to show one month at a time. 

Great plugin so far by the way, very very helpful!

**Comment by a-am** [comment]
@etx try downloading newer version.  I was able to get it to work locally with using both "byYear" and "byMonth".

**Comment by etx** [comment]
I did a git pull and looks like it is working. I should have tried that before posting an issue, sorry about that.
