### ISSUE TITLE
Repeating Events

### ISSUE THREAD

**Issue by justjoolz** [tippingmedia/craft.events#6]
Whenever I try to add repeating event I get the following error:

Fatal error: Class 'Recurr\Rule' not found in /home/j00lz/www/bodhihearts.net/plugins/events/services/Events_EventManageService.php on line 784

**Comment by a-am** [comment]
Have you added the https://github.com/simshaun/recurr library to the vendors folder?

**Comment by justjoolz** [comment]
I missed out the /simshaun directory.
up and running now thanks :)

**Comment by a-am** [comment]
Glad your up and running!

**Comment by justjoolz** [comment]
You&#8217;ve been invited!

On Airbnb you can discover unique places to stay from local hosts, all over the world.
Simply sign up to get RM91 off your first trip of RM272 or more.


Sign up
http://www.airbnb.com/c/jjoolz?euid=5b193271-232b-ba4d-dda6-de3453b318df&ri=16848819&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwMWI3YWY2MGE3MDQwZjlkMzM3NWM4ZGViODI3ZTBjYjc4M2RlNTAwZWRlNDg2OTJjZjAwMDAwMDAxMTEwNjVlMjc5MmExNjljZTAzODQ1MjFjQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiI1YjE5MzI3MS0yMzJiLWJhNGQtZGRhNi1kZTM0NTNiMzE4ZGYifQ==&mac=6BzciKI83Bbk8tPceL4HtI35s_Q=

### Airbnb ###

**Comment by justjoolz** [comment]
Remember to claim your credit!

Your friend Just gave you RM90 to try out Airbnb, a marketplace where you can rent unique, local accommodations, on any budget, anywhere in the world.
You haven't claimed your credit yet - just click below and it will get automatically applied to your first trip!

Minimum booking value RM270.

Sign up
http://www.airbnb.com/c/jjoolz?euid=aaf5c0d4-1118-6c2a-386e-28acb1898db8&ri=16848819&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwMWI3YWY2MGE3MDQwZjlkMzM3NWM4ZGViODI3ZTBjYjc4M2RlNTAwZWRlNDg2OTJjZjAwMDAwMDAxMTEwNjVlMjc5MmExNjljZTAzODQ1MjFjQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbl9yZW1pbmRlciIsInV1aWQiOiJhYWY1YzBkNC0xMTE4LTZjMmEtMzg2ZS0yOGFjYjE4OThkYjgifQ==&mac=SnwObx-0qOfc4bxlGiSh5SKTixk=

### Airbnb ###
