### ISSUE TITLE
Recurring events producing fixed dates.

### ISSUE THREAD

**Issue by justjoolz** [tippingmedia/craft.events#7]
When I add an recurrence rule to an event, the only field that appears to work correctly is the number of occurrences.

The dates returned when querying always start from '2017-02-03' no matter what rule/options I select.
And follow daily for the number of occurrences I select.

Any idea what could be causing this?

**Comment by justjoolz** [comment]
(and repeat daily from this date)

**Comment by a-am** [comment]
What was the start date, end date and recurrence rule you selected?

**Comment by justjoolz** [comment]
I've tried various combinations but whenever there is a reoccurence rule
the dates of the recurring events are very strange.

Fo example for an event that starts on 01/03/2015
On the popup the start date is fixed as the same date as the event.
Selecting : Daily, every 7 days, ends have 3 occurrences

I get the following dates:

{ title: 'test', url: 'http://bodhihearts.dev/activities/2015/test', start:
'2015-03-01T11:30:00+08:00', end: '2015-03-01T13:00:00+08:00',

 subtitle: 'test', description: 'test',
 } , { title: 'test', url: 'http://bodhihearts.dev/activities/2015/test',
start: '2017-04-09T11:03:00+08:00', end: '2017-04-09T13:00:00+08:00',

 subtitle: 'test', description: 'test',
 } , { title: 'test', url: 'http://bodhihearts.dev/activities/2015/test',
start: '2017-04-16T11:03:00+08:00', end: '2017-04-16T13:00:00+08:00',

 subtitle: 'test', description: 'test',
 }

**Comment by justjoolz** [comment]
Example 2:

Start date 2015-01-17 
daily every 1 day for 10 times:

{
					    start: '2015-03-17T19:00:00+08:00',
					    end: '2015-03-18T04:00:00+08:00',
					}
					,				    	
					{
					    start: '2016-06-04T11:03:00+08:00',
					    end: '2016-06-04T04:00:00+08:00',
					}
					,				    	
					{
					    start: '2016-06-05T11:03:00+08:00',
					    end: '2016-06-05T04:00:00+08:00',
					}
					,				    	
					{
					    start: '2016-06-06T11:03:00+08:00',
					    end: '2016-06-06T04:00:00+08:00',
					}
					,				    	
					{
					    start: '2016-06-07T11:03:00+08:00',
					    end: '2016-06-07T04:00:00+08:00',
					}
					,				    	
					{
					    start: '2016-06-08T11:03:00+08:00',
					    end: '2016-06-08T04:00:00+08:00',
					}
					,				    	
					{
					    start: '2016-06-09T11:03:00+08:00',
					    end: '2016-06-09T04:00:00+08:00',
					}
					,				    	
					{
					    start: '2016-06-10T11:03:00+08:00',
					    end: '2016-06-10T04:00:00+08:00',
					}
					,				    	
					{
					    start: '2016-06-11T11:03:00+08:00',
					    end: '2016-06-11T04:00:00+08:00',
					}
					,				    	
					{
					    start: '2016-06-12T11:03:00+08:00',
					    end: '2016-06-12T04:00:00+08:00',
					}

**Comment by justjoolz** [comment]
PS: the long date format is output from 
   {{ e.startDate  | date("c") }}

**Comment by a-am** [comment]
Try setting Craft's timezone to UTC.

**Comment by justjoolz** [comment]
Just tried that and it makes no difference :(

**Comment by justjoolz** [comment]
Actually the repeat by days is working now but setting weekly still makes
it start years in the future and changes the time of the event too

**Comment by a-am** [comment]
@justjoolz what is the weekly repeat schedule you are setting specifically?

**Comment by justjoolz** [comment]
Hi I've been on holiday but back to work on this now, still having issues
regardless of what repeat schedule settings I select the times and dates
don't seem to be accurate.
Can I send you some login details to have a look perhaps?

**Comment by a-am** [comment]
Currently we are in the middle of a large project. We have been in the process of redoing the events plugin.  As soon as we have time I will take a look to see if we can figure out your issue.

**Comment by justjoolz** [comment]
Many thanks, any idea approximately when that will be?
I've tried 3 different events plugins and they all have issues :(

**Comment by justjoolz** [comment]
The repeat by days also does not seem to work :( 

Here is are a couple of examples as it might be something obvious that you can spot easily....

![screenshot from 2015-04-17 14 07 54](https://cloud.githubusercontent.com/assets/112559/7196798/37169730-e50b-11e4-9b26-c365df8e8baf.png)


![screenshot from 2015-04-17 14 08 00](https://cloud.githubusercontent.com/assets/112559/7196801/40e9aab8-e50b-11e4-8ba1-1e5fdd8e0ff5.png)


The dates of all the repeated events output are skewed, first event is fine but all subsequent events have the wrong time and sometimes dates too:

The minutes of the start time seem to follow the hour... ie 12:30 is replaced with 12:12 for the repeating events

First event:
start: '2015-04-02T10:00:00+00:00',
First Repeat (of 7 that are in the past):
start: '2015-02-12T10:10:00+00:00'


Example 2:

![screenshot from 2015-04-17 14 24 50](https://cloud.githubusercontent.com/assets/112559/7196978/920123fc-e50d-11e4-9dd3-bb85a4408b64.png)

![screenshot from 2015-04-17 14 24 55](https://cloud.githubusercontent.com/assets/112559/7196980/95ed0300-e50d-11e4-9432-3eb13c897665.png)


In this example the start time does the same thing but the dates of the first repeated event jumps ahead 2 months, and behind by 2 days from what is expected.
First Event
start: '2015-04-06     19:30
First Repeat
start: '2015-06-11     19:19

After that it repeats consistently every 7 days with the same 'minutes following hours' time.


Trying to see the pattern here.... the start time seems obvious but the dates I can't work out....

another few examples with the same every 7 days settings....


Example 3:

First event:
Apr 7th 6:30 PM to 8:30 PM
First Repeat:
Jul 11th 6:18 PM to 8:30 PM


Example 4:

First Event:
Apr 6th 10:30 AM to 12:00 PM
First Repeat:
Jun 11th 10:10 AM to 12:00 PM


Example 5:

First Event:
Apr 5th 7:00 PM to 9:00 PM
First Repeat:
May 11th 7:19 PM to 9:00 PM





The code I'm using to populate the calendar:

```
{% set events = craft.Events.getAllEvents(order,filters,dateFilters) %}

{% set calendarSetupJs %}
// </style> 
/* <script> */
	$(document).ready(function() {
		
		$('#calendar').fullCalendar({
			
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},

			minTime: "09:00:00",
			maxTime: "22:00:00",

			// defaultDate: '2014-11-12',
			// editable: true,
			eventLimit: true, // allow "more" link when too many events
			events: [
				{# For Events #}

				{% for e in events %}    	
					{
					    title: '{{ e.entry.title }}',
					    url: '{{ e.entry.url }}',
					    start: '{{ e.startDate  | date("c") }}',
					    end: '{{ e.endDate  | date("c") }}',


					    {% for teachers in e.entry.teacherBiodata %}
            				{% for images in teachers.image %}
					    		image: '<img class="icon alt major" src="{{ images.thumb.url }}"> ',
					    	{% endfor %}
					    {% endfor %}

					    subtitle: '{{ e.entry.subtitle }}',
					    description: '{{ e.entry.subtitle }}',

					    {% for category in e.entry.programCategory %}
					    	{% if category.level == 1 %}
							    {% switch category.title %}
							    	{% case "Spiritual" %}
							    		colour: 'orange'
							    	{% case "Welfare" %}
							    		colour: 'green'
							    	{% case "Wellness" %}
							    		colour: 'blue'
							    	{% default %}
							    		colour: 'black'
							    {% endswitch %}					    	
							{% endif %}
					    {% endfor %}

					}
					{% if not loop.last %},{% endif %}
				{% endfor %}
			],

		    // Called each time an event is written to the screen
		    // add the popup data here....
		    eventRender: function(event, element) {
		        element.css( "background-color", event.colour );
		        
		        popupData = event.title + 
		        			event.image;

		        event.title = event.title;

		        element.find('.fc-title').html(event.title);

		        element.attr('href', 'javascript:void(0);');
		        element.click(function() {
		        	// test to see if length of event spans multiple days 
		        	if( event.start.format('MMM Do')==event.end.format('MMM Do') ) {
		        		// 1 day event 
		        		$("#startTime").html(
		        			moment(event.start).format('MMM Do h:mm A') + ' to ' + moment(event.end).format('h:mm A')
		        		) 
		        	} else {
			            $("#startTime").html(moment(event.start).format('MMM Do h:mm A'));
			            $("#endTime").html(moment(event.end).format('MMM Do h:mm A'));
		        	}
		        	    	        		
		            $("#eventInfo").html(event.description);
		            $("#eventSpeakerImg").html(event.image);
		            $("#eventLink").attr('href', event.url);
		            $("#eventContent").dialog({ modal: true, title: event.title, width:500});
		        });

		    }
		});	
	});
// </script>
{% endset %} 
```

Full output of the page here:
http://bhs.dharmaavenue.net/programs

**Comment by justjoolz** [comment]
You&#8217;ve been invited!

On Airbnb you can discover unique places to stay from local hosts, all over the world.
Simply sign up to get RM91 off your first trip of RM363 or more.


Sign up
http://www.airbnb.com/c/jjoolz?euid=19da5861-f5c3-d8c7-e0b7-02f9f885348d&ri=16848824&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwMWI3YWZhNWYxYWM5N2IxZWZlNmM5YTYxMTA2MzNlZTE2NjdjNWUxNzRjMTU1OTJjZjAwMDAwMDAxMTEwNzAwY2U5MmExNjljZTAzODRiOGRjQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiIxOWRhNTg2MS1mNWMzLWQ4YzctZTBiNy0wMmY5Zjg4NTM0OGQifQ==&mac=sJCf9LWF2Su51HHNu0QHMc1CwCM=

### Airbnb ###

**Comment by justjoolz** [comment]
You&#8217;ve been invited!

On Airbnb you can discover unique places to stay from local hosts, all over the world.
Simply sign up by April 28, 2015 to get RM91 off your first trip of RM272 or more.


Sign up
http://www.airbnb.com/c/jjoolz?euid=d9dec990-56a1-df7f-29c1-6630167e3c3f&ri=16848831&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwMWI3YWYxMzYwNTA5OGNkMjEwN2NhNmJjMDhmNDVkNWJmNTg1YzMyMzc2MjMwOTJjZjAwMDAwMDAxMTEwZGIwM2Q5MmExNjljZTAzODRiOGRjQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiJkOWRlYzk5MC01NmExLWRmN2YtMjljMS02NjMwMTY3ZTNjM2YifQ==&mac=zFXEGZknWkQ1X-kuvVTPzSOB29M=

### Airbnb ###

**Comment by justjoolz** [comment]
You&#8217;ve been invited!

On Airbnb you can discover unique places to stay from local hosts, all over the world.
Simply sign up by April 28, 2015 to get RM91 off your first trip of RM363 or more.


Sign up
http://www.airbnb.com/c/jjoolz?euid=51348b13-b82a-e4ea-9c0d-f4057c28eb79&ri=16848814&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwMWI3YWZjMTAxMGUxNjM3YmM2OGNjMDhiZmM2OGRlZTc1ZDQyZmFmY2JiMDUxOTJjZjAwMDAwMDAxMTEwOWQyOGI5MmExNjljZTAzODRiOGRjQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiI1MTM0OGIxMy1iODJhLWU0ZWEtOWMwZC1mNDA1N2MyOGViNzkifQ==&mac=1t_9Bm6R3XuZzLY-eeGS8U7YG9E=

### Airbnb ###

**Comment by justjoolz** [comment]
Remember to claim your credit!

Your friend Just gave you RM90 to try out Airbnb, a marketplace where you can rent unique, local accommodations, on any budget, anywhere in the world.
You haven't claimed your credit yet - just click below and it will get automatically applied to your first trip!

Minimum booking value RM270.

Sign up
http://www.airbnb.com/c/jjoolz?euid=13bd4b1f-f757-d7da-fa8f-8de808655cbd&ri=16848831&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwMWI3YWYxMzYwNTA5OGNkMjEwN2NhNmJjMDhmNDVkNWJmNTg1YzMyMzc2MjMwOTJjZjAwMDAwMDAxMTEwZGIwM2Q5MmExNjljZTAzODRiOGRjQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbl9yZW1pbmRlciIsInV1aWQiOiIxM2JkNGIxZi1mNzU3LWQ3ZGEtZmE4Zi04ZGU4MDg2NTVjYmQifQ==&mac=rfVT-A9ILW4CV3N-r-m3vFrK5QE=

### Airbnb ###

**Comment by justjoolz** [comment]
Remember to claim your credit!

Your friend Just gave you RM90 to try out Airbnb, a marketplace where you can rent unique, local accommodations, on any budget, anywhere in the world.
You haven't claimed your credit yet - just click below and it will get automatically applied to your first trip!

Minimum booking value RM360.

Sign up
http://www.airbnb.com/c/jjoolz?euid=fea5acd3-b804-7814-0f39-f9391ce9d056&ri=16848824&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwMWI3YWZhNWYxYWM5N2IxZWZlNmM5YTYxMTA2MzNlZTE2NjdjNWUxNzRjMTU1OTJjZjAwMDAwMDAxMTEwNzAwY2U5MmExNjljZTAzODRiOGRjQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbl9yZW1pbmRlciIsInV1aWQiOiJmZWE1YWNkMy1iODA0LTc4MTQtMGYzOS1mOTM5MWNlOWQwNTYifQ==&mac=JZomrZCAzhRKZjO4TqQbBRFTNRU=

### Airbnb ###

**Comment by justjoolz** [comment]
Remember to claim your credit!

Your friend Just gave you RM90 to try out Airbnb, a marketplace where you can rent unique, local accommodations, on any budget, anywhere in the world.
You haven't claimed your credit yet - just click below and it will get automatically applied to your first trip!

Minimum booking value RM360.

Sign up
http://www.airbnb.com/c/jjoolz?euid=f19207c6-3008-5d75-cd9a-1fd08b4f62a6&ri=16848814&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDAwMWI3YWZjMTAxMGUxNjM3YmM2OGNjMDhiZmM2OGRlZTc1ZDQyZmFmY2JiMDUxOTJjZjAwMDAwMDAxMTEwOWQyOGI5MmExNjljZTAzODRiOGRjQHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbl9yZW1pbmRlciIsInV1aWQiOiJmMTkyMDdjNi0zMDA4LTVkNzUtY2Q5YS0xZmQwOGI0ZjYyYTYifQ==&mac=wyiMRrux_99Rb1uJS2uqBgzsNsg=

### Airbnb ###

**Comment by justjoolz** [comment]
Any chance at looking at this issue?
I have a site ready for launch, and am keen to use this plugin... currently
have multiple entries for events on the site which is less than ideal.

**Comment by a-am** [comment]
@justjoolz we have stopped maintenance on this version due to resources. Our efforts have been towards a plugin rewrite.  We are close to having our newest version to a closed beta release, would you be interested in being apart of that?

**Comment by justjoolz** [comment]
Very much so :) I'm keen to get this feature sorted asap thanks :)

**Comment by justjoolz** [comment]
@a-am Any news on the closed beta release? I have a few new projects which revolve around events and would like to give your plugin a whirl :)

**Comment by timkelty** [comment]
>>> @a-am Any news on the closed beta release? I have a few new projects which revolve around events and would like to give your plugin a whirl :)

Same here!

**Comment by a-am** [comment]
We are squashing a few bugs.  We will need the plugin for several projects here soon as well so I will post our beta signup site soon.

**Comment by idahotallpaul** [comment]
Hi @a-am, what is the timeline for the next release? Scoping an event heavy project and I'd like to give the plugin a shot as well. Thanks.

**Comment by a-am** [comment]
Our goal is to have our private beta ready by the end of the month.  I will post a link to a sign up form when we are ready. Thanks for your patience and interest!

**Comment by justjoolz** [comment]
Great news, thanks for the update.

**Comment by a-am** [comment]
You can now start using our new plugin through our beta program.  Sign-up here http://tippingmedia.com/craft/.  You also have access to documentation at that link. You should receive an email when you sign up with instructions to download and communicate any issues back to us.
